trade:
  symbol: BTCUSDT
  interval: 15m
  qty: 0.00025 
  close_trade: False

rsi:
  rsi_up: 70
  rsi_down: 30
  rsi_period: 9
  rsi_divergence: False

bollinger:
  boll_period: 10
  boll_dev_factor: 2
  profit_boll_middle: True
  double_boll_validation: False

macd:
  macd_divergence: False
  full_macd: False
  enable_macd: True
